default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: sample_app_development
  pool: 5
  timeout: 5000
  username: 'vumh'
  password: '123456'

  
test:
  <<: *default
  database: sample_app_test
  pool: 5
  timeout: 5000
  username: 'vumh'
  password: '123456'

production:
  <<: *default
  database: sample_app_production
  username: vumh
  password: '123456'
